### ISSUE TITLE
runtime issue

### ISSUE THREAD

**Issue by AndssY** [feizc/DiS#2]
Thanks for interesting work. 
Since diffusion models typically have slow inference times, I'm curious if modifying the U-Net architecture to incorporate Mamba blocks changes the inference speed. Does it make the model slower or faster? And to what extent does it affect the speed?

**Comment by feizc** [comment]
Sorry, we have not done a detailed experiments comparison, but we can provide the following points: 
1. According to the original Mamaba paper, the inference speed is improved by about 4 times under the same parameters settings.
<img width="697" alt="image" src="https://github.com/feizc/DiS/assets/37614046/307eb0ca-4b79-4c50-9f09-e17b86d1e696">
2. The diffusion process can be significantly accelerated with advanced noise schedule, e.g. DPM solver, which is compatible with our models.
